// src/lib/components/ErrorBoundary.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { onDestroy } from 'svelte';

  interface Props {
    children: Snippet;
  }

  let { children }: Props = $props();

  let hasError = $state(false);
  let error = $state<Error | null>(null);

  function handleError(event: ErrorEvent) {
    event.preventDefault();
    hasError = true;
    error = event.error;
    console.error('[ErrorBoundary] Caught an error:', event.error);
  }

  if (typeof window !== 'undefined') {
    window.addEventListener('error', handleError);
  }

  onDestroy(() => {
    if (typeof window !== 'undefined') {
      window.removeEventListener('error', handleError);
    }
  });

  function handleRetry() {
    hasError = false;
    error = null;
  }
</script>

{#if hasError}
  <div
    role="alert"
    style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; padding: 32px; text-align: center; color: var(--color-text-primary);"
  >
    <span style="font-size: 4rem; margin-bottom: 16px;">😿</span>
    <h1 style="font-size: 1.5rem; margin-bottom: 8px;">Something went wrong</h1>
    <p
      style="color: var(--color-text-secondary); margin-bottom: 24px; max-width: 400px;"
    >
      The cat knocked something over. Please try again.
    </p>
    <button
      onclick={handleRetry}
      style="padding: 10px 24px; border-radius: 8px; border: none; background: var(--color-accent-gradient); color: white; font-weight: 600; cursor: pointer; font-size: 1rem;"
    >
      Try Again
    </button>
  </div>
{:else}
  {@render children()}
{/if}

// src/components/ErrorBoundary/ErrorBoundary.tsx
/**
 * ErrorBoundary — catches render errors and displays a friendly fallback UI.
 *
 * Class component because React error boundaries require getDerivedStateFromError
 * and componentDidCatch, which are not available in function components.
 */

import { Component } from 'react';
import type { ErrorInfo, ReactNode } from 'react';

interface ErrorBoundaryProps {
  readonly children: ReactNode;
}

interface ErrorBoundaryState {
  readonly hasError: boolean;
  readonly error: Error | null;
}

export class ErrorBoundary extends Component<
  ErrorBoundaryProps,
  ErrorBoundaryState
> {
  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error };
  }

  componentDidCatch(error: Error, errorInfo: ErrorInfo): void {
    console.error('[ErrorBoundary] Caught an error:', error, errorInfo);
  }

  private handleRetry = (): void => {
    this.setState({ hasError: false, error: null });
  };

  render(): ReactNode {
    if (this.state.hasError) {
      return (
        <div
          role="alert"
          style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            minHeight: '100vh',
            padding: '32px',
            textAlign: 'center',
            color: 'var(--color-text-primary)',
          }}
        >
          <span style={{ fontSize: '4rem', marginBottom: '16px' }}>😿</span>
          <h1 style={{ fontSize: '1.5rem', marginBottom: '8px' }}>
            Something went wrong
          </h1>
          <p
            style={{
              color: 'var(--color-text-secondary)',
              marginBottom: '24px',
              maxWidth: '400px',
            }}
          >
            The cat knocked something over. Please try again.
          </p>
          <button
            onClick={this.handleRetry}
            style={{
              padding: '10px 24px',
              borderRadius: '8px',
              border: 'none',
              background: 'var(--color-accent-gradient)',
              color: 'white',
              fontWeight: 600,
              cursor: 'pointer',
              fontSize: '1rem',
            }}
          >
            Try Again
          </button>
        </div>
      );
    }

    return this.props.children;
  }
}
