// src/lib/components/ActionBar.svelte
<script lang="ts">
  interface Props {
    onAddClick: () => void;
    onDeleteClick: () => void;
    onExportClick: () => void;
    selectedCount: number;
    isDeleteDisabled: boolean;
    isExportDisabled: boolean;
  }

  let {
    onAddClick,
    onDeleteClick,
    onExportClick,
    selectedCount,
    isDeleteDisabled,
    isExportDisabled,
  }: Props = $props();

  let deleteButtonClasses = $derived(
    [
      'action-bar__button',
      'action-bar__button--danger',
      isDeleteDisabled ? 'action-bar__button--disabled' : '',
    ]
      .filter(Boolean)
      .join(' '),
  );

  let exportButtonClasses = $derived(
    [
      'action-bar__button',
      'action-bar__button--secondary',
      isExportDisabled ? 'action-bar__button--disabled' : '',
    ]
      .filter(Boolean)
      .join(' '),
  );
</script>

<div
  class="action-bar"
  id="action-bar"
  role="toolbar"
  aria-label="Expense actions"
>
  <button
    id="add-expense-button"
    class="action-bar__button action-bar__button--primary"
    onclick={onAddClick}
    type="button"
  >
    <span class="action-bar__button-icon" aria-hidden="true">+</span>
    Add Expense
  </button>

  <button
    id="delete-expense-button"
    class={deleteButtonClasses}
    onclick={onDeleteClick}
    disabled={isDeleteDisabled}
    type="button"
    aria-label={`Delete ${selectedCount} selected expense${selectedCount !== 1 ? 's' : ''}`}
  >
    <span class="action-bar__button-icon" aria-hidden="true">🗑️</span>
    Delete Expense
    {#if selectedCount > 0}
      <span class="action-bar__badge" aria-hidden="true">
        {selectedCount}
      </span>
    {/if}
  </button>

  <button
    id="export-csv-button"
    class={exportButtonClasses}
    onclick={onExportClick}
    disabled={isExportDisabled}
    type="button"
    aria-label="Export all expenses as CSV"
  >
    <span class="action-bar__button-icon" aria-hidden="true">⬇</span>
    Export CSV
  </button>
</div>

<style lang="scss">
  /*
   * ActionBar — BEM Block: .action-bar
   */

  .action-bar {
    display: flex;
    align-items: center;
    gap: var(--space-sm);
    margin-bottom: var(--space-md);

    &__button {
      display: inline-flex;
      align-items: center;
      gap: var(--space-sm);
      padding: var(--space-sm) var(--space-lg);
      border: none;
      border-radius: var(--radius-md);
      font-family: var(--font-family);
      font-size: var(--font-size-sm);
      font-weight: var(--font-weight-semibold);
      cursor: pointer;
      transition:
        transform var(--transition-fast),
        box-shadow var(--transition-fast),
        opacity var(--transition-fast);
      white-space: nowrap;
      line-height: 1;
      height: var(--button-height);

      &:active:not(&--disabled) {
        transform: scale(0.97);
      }

      /* Primary (Add Expense) */
      &--primary {
        background: var(--color-accent-gradient);
        color: white;
        box-shadow: var(--shadow-accent);

        &:hover:not(.action-bar__button--disabled) {
          box-shadow: 0 6px 24px rgba(168, 85, 247, 0.4);
          transform: translateY(-1px);
        }
      }

      /* Danger (Delete) */
      &--danger {
        background: var(--color-danger-bg);
        color: var(--color-danger);
        border: 1px solid rgba(239, 68, 68, 0.2);

        &:hover:not(.action-bar__button--disabled) {
          background: rgba(239, 68, 68, 0.18);
          border-color: rgba(239, 68, 68, 0.4);
        }
      }

      /* Secondary (Export) */
      &--secondary {
        background: var(--color-bg-glass);
        color: var(--color-text-secondary);
        border: 1px solid var(--color-bg-glass-border);

        &:hover:not(.action-bar__button--disabled) {
          background: var(--color-bg-glass-hover);
          color: var(--color-text-primary);
          border-color: rgba(255, 255, 255, 0.16);
        }
      }

      /* Disabled state */
      &--disabled {
        opacity: 0.4;
        cursor: not-allowed;
        transform: none;
        box-shadow: none;
      }
    }

    &__button-icon {
      font-size: var(--font-size-md);
      line-height: 1;
    }

    &__badge {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      min-width: var(--badge-size);
      height: var(--badge-size);
      padding: 0 var(--space-xs);
      border-radius: var(--radius-full);
      background: var(--color-danger);
      color: white;
      font-size: var(--font-size-xs);
      font-weight: var(--font-weight-bold);
      line-height: 1;
    }

    /* Mid-range tablet (500px – 767px): keep buttons in a row, just compress padding */
    @media (min-width: 500px) and (max-width: 767px) {
      .action-bar__button {
        padding: var(--space-sm) var(--space-md);
      }
    }

    /* Small mobile (< 500px): reflow buttons to a clean primary/secondary grid */
    @media (max-width: 499px) {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: var(--space-xs);
      margin-bottom: var(--space-md);

      .action-bar__button {
        width: 100%;
        justify-content: center;

        /* Add Expense button (primary) spans both columns */
        &--primary {
          grid-column: 1 / -1;
        }

        /* Secondary/Danger buttons (Delete, Export) stay side-by-side */
        &--danger,
        &--secondary {
          grid-column: span 1;
          padding: var(--space-sm) var(--space-xs);
          font-size: 0.8rem;
          gap: var(--space-xs);
        }
      }
    }
  }
</style>

// src/components/ActionBar/ActionBar.tsx
/**
 * ActionBar — Add/Delete/Export action buttons.
 *
 * Single Responsibility: renders action buttons and delegates click handlers.
 * ISP: receives only the callbacks and state it needs.
 */

import './ActionBar.css';

interface ActionBarProps {
  readonly onAddClick: () => void;
  readonly onDeleteClick: () => void;
  readonly onExportClick: () => void;
  readonly selectedCount: number;
  readonly isDeleteDisabled: boolean;
  readonly isExportDisabled: boolean;
}

export function ActionBar({
  onAddClick,
  onDeleteClick,
  onExportClick,
  selectedCount,
  isDeleteDisabled,
  isExportDisabled,
}: ActionBarProps) {
  const deleteButtonClasses = [
    'action-bar__button',
    'action-bar__button--danger',
    isDeleteDisabled ? 'action-bar__button--disabled' : '',
  ]
    .filter(Boolean)
    .join(' ');

  const exportButtonClasses = [
    'action-bar__button',
    'action-bar__button--secondary',
    isExportDisabled ? 'action-bar__button--disabled' : '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className="action-bar" id="action-bar" role="toolbar" aria-label="Expense actions">
      <button
        id="add-expense-button"
        className="action-bar__button action-bar__button--primary"
        onClick={onAddClick}
        type="button"
      >
        <span className="action-bar__button-icon" aria-hidden="true">+</span>
        Add Expense
      </button>

      <button
        id="delete-expense-button"
        className={deleteButtonClasses}
        onClick={onDeleteClick}
        disabled={isDeleteDisabled}
        type="button"
        aria-label={`Delete ${selectedCount} selected expense${selectedCount !== 1 ? 's' : ''}`}
      >
        <span className="action-bar__button-icon" aria-hidden="true">🗑️</span>
        Delete Expense
        {selectedCount > 0 && (
          <span className="action-bar__badge" aria-hidden="true">
            {selectedCount}
          </span>
        )}
      </button>

      <button
        id="export-csv-button"
        className={exportButtonClasses}
        onClick={onExportClick}
        disabled={isExportDisabled}
        type="button"
        aria-label="Export all expenses as CSV"
      >
        <span className="action-bar__button-icon" aria-hidden="true">⬇</span>
        Export CSV
      </button>
    </div>
  );
}
